trigger:
  branches:
    include:
      - DEV
      - QA
      - main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: npm install
  displayName: 'Install dependencies'

- script: npx eslint vul.js --fix
  displayName: 'Ajustando falhas com ESLint'

- script: npx eslint vul.js
  displayName: 'Run ESLint'

- script: |
    echo Acabou!
    echo † Dead line † 
  displayName: 'Fim da Execução'