trigger:
  branches:
    include:
      - DEV
      - QA
      - main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: npm install
  displayName: 'Install dependencies'

- script: npx eslint vul.js --fix
  displayName: 'Ajustando falhas com ESLint'

- script: npx eslint vul.js
  displayName: 'Run ESLint'

- script: |
    echo Acabou!
    echo † Dead line † 
  displayName: 'Fim da Execução'

- script: |
    if ! git show-ref --quiet refs/heads/DEV; then
      git checkout -b DEV
      git push -u origin DEV
    fi
  displayName: 'Create DEV branch if not exists'

- script: |
    if ! git show-ref --quiet refs/heads/QA; then
      git checkout -b QA
      git push -u origin QA
    fi
  displayName: 'Create QA branch if not exists'

- script: |
    if ! git show-ref --quiet refs/heads/PROD; then
      git checkout -b PROD
      git push -u origin PROD
    fi
  displayName: 'Create PROD branch if not exists'

- script: git checkout DEV
  displayName: 'Switch to DEV branch'

- script: git push origin DEV
  displayName: 'Push to DEV branch'

- script: git checkout QA
  displayName: 'Switch to QA branch'

- script: git push origin QA
  displayName: 'Push to QA branch'

- script: |
    echo Running Checkmarx scan on QA branch
    # Comandos para executar o scan do Checkmarx na branch de QA
  displayName: 'Checkmarx Scan - QA branch'

- script: git checkout main
  displayName: 'Switch to main branch'

- script: git push origin main
  displayName: 'Push to main branch'

- script: |
    echo Running ESLint and Checkmarx scan on PROD branch
    # Comandos para executar o ESLint e o scan do Checkmarx na branch de PROD
  displayName: 'ESLint and Checkmarx Scan - PROD branch'
